# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build work-whiz`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t work-whiz`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system work-whiz && \
          adduser --system -G work-whiz work-whiz

COPY dist/work-whiz work-whiz/
RUN chown -R work-whiz:work-whiz .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix work-whiz --omit=dev -f install

CMD [ "node", "work-whiz" ]
